### ISSUE TITLE
TypeError: Cannot read property 'read' of undefined

### ISSUE THREAD

**Issue by bertique** [iler/node-airthings-waveplus#3]
When running the sample, it discovers my Wave and it prints the proper serial number of the device (so I know it was found).

Though then immediately I get an error. Any idea what might be wrong? Looks like for some reason peripheral.discoverSomeServicesAndCharacteristics is not returning characteristics, but is also not throwing an error.

/home/pi/wave-node/node_modules/airthings-waveplus/waveplus.js:101
      characteristics[0].read((error, data) => {
                         ^

TypeError: Cannot read property 'read' of undefined
    at /home/pi/wave-node/node_modules/airthings-waveplus/waveplus.js:101:26
    at /home/pi/wave-node/node_modules/@abandonware/noble/lib/peripheral.js:119:13
    at Service.<anonymous> (/home/pi/wave-node/node_modules/@abandonware/noble/lib/service.js:56:7)
    at Object.onceWrapper (events.js:422:26)
    at Service.emit (events.js:315:20)
    at Noble.onCharacteristicsDiscover (/home/pi/wave-node/node_modules/@abandonware/noble/lib/noble.js:398:13)
    at NobleBindings.emit (events.js:315:20)
    at NobleBindings.onCharacteristicsDiscovered (/home/pi/wave-node/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:368:8)
    at Gatt.emit (events.js:315:20)
    at Object.callback (/home/pi/wave-node/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:515:12)

**Comment by bertique** [comment]
Figured it out. I have a Wave (not the Wave Plus). After changing the uuid it works:

For reference, this is the line I replaced in waveplus.js:
this.uuid = ['b42e2a68ade711e489d3123b93f75cba'];
with
this.uuid = ['b42e4dccade711e489d3123b93f75cba'];
